# Simple Kubernetes Pod to deploy the app contained in ryandodson/k8sdemo:1.0
apiVersion: v1
kind: Pod
metadata:
  name: ryans-pod2
  labels:
    app: web
spec:
  containers:
    - name: web-ctr
      image: ryandodson/k8sdemo:2.0
      ports:
        - containerPort: 8080
